---

- name: Deploying playbook

  hosts: all

  become: true

  vars_files:

    - ./group_vars/webservers/vars.yml

  roles:

    - role: geerlingguy.pip

  tasks:

    - name: Copy .env file

      ansible.builtin.template:

        src: docker.j2

        dest: .env

        owner: root

        group: root

        mode: u=rw,g=r,o=r

    - name: Deploy redmine app

      community.docker.docker_container:

        name: redmine

        image: redmine

        auto_remove: true

        env_file:

          .env

        ports:

          - "{{ app_port }}:{{ app_port }}"

- name: Install Datadog monitoring

  hosts: webservers

  gather_facts: true

  become: true

  vars_files:

    - ./group_vars/webservers/vars.yml

  vars:

    datadog_api_key: "{{ datadog_api_key }}"

    datadog_site: "{{ datadog_site }}"

    datadog_port: "{{ app_port }}"

    app_key: "{{ datadog_app_key }}"

  roles:

    - role: DataDog.datadog

  tasks:

    - name: Copy configuration file

      ansible.builtin.template:

        src: ./templates/datadog.yaml.j2

        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml

        owner: root

        group: root

        mode: u=rw,g=r,o=r

    - name: Restart agent

      ansible.builtin.service:

        name: datadog-agent

        state: restarted