---

- name: Deploying playbook

  hosts: all

  become: true

  vars:

    pip_install_packages:

      - name: docker

  vars_files:

    - ./ansible/group_vars/webservers/vault.yml

  roles:

    - role: geerlingguy.pip

  tasks:

    - name: Deploy redmine app

      community.docker.docker_container:

        name: "{{ APP_NAME }}"

        image: redmine

        auto_remove: true

        ports:

          - "3000:3000"

        env:

          REDMINE_DB_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"

          REDMINE_DB_PORT: "{{ REDMINE_DB_PORT }}"

          REDMINE_DB_POSTGRES: "{{ REDMINE_DB_POSTGRES }}"

          REDMINE_DB_USERNAME: "{{ REDMINE_DB_USERNAME }}"

- name: Install Datadog monitoring

  hosts: webservers

  gather_facts: true

  become: true

  vars_files:

    - ./ansible/group_vars/webservers/vault.yml

  vars:

    datadog_api_key: "{{ DATADOG_API_KEY }}"

    datadog_site: "{{ DATADOG_SITE }}"

    datadog_port: "{{ DATADOG_PORT }}"

    app_key: "{{ DATADOG_APP_KEY }}"

  roles:

    - role: DataDog.datadog

  tasks:

    - name: Copy configuration file

      ansible.builtin.template:

        src: ./ansible/templates/datadog.yaml.j2

        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml

        owner: root

        group: root

        mode: u=rw,g=r,o=r

    - name: Restart agent

      ansible.builtin.service:

        name: datadog-agent

        state: restarted