---

- name: Setup (python3)

  hosts: all

  become: true

  vars:

    user: "{{ ansible_user }}"

  tasks:

    - name: Check if python is already installed

      ansible.builtin.command: python3 --version

      register: python_version_result

    - name: Install Python

      when: python_version_result.failed

      ansible.builtin.apt:

        name: python{{ python_version }}

        state: present

        update_cache: true

    - name: Install docker

      when: not python_version_result.failed

      block:

        - name: Update apt cache

          ansible.builtin.apt:

            force_apt_get: true

            upgrade: true

            update_cache: true

            cache_valid_time: 604800 #A week

        - name: Install required packages for Docker

          ansible.builtin.apt:

            force_apt_get: true

            force: true

            pkg:

              - ca-certificates

              - curl

              - gnupg

              - lsb-release

        - name: Create directory for Docker keyrings

          ansible.builtin.shell: mkdir -m 0755 -p /etc/apt/keyrings

        - name: Download Docker GPG key

          ansible.builtin.apt_key:

            url: https://download.docker.com/linux/ubuntu/gpg

            keyring: /etc/apt/keyrings/docker.gpg

            state: present

        - name: Add Docker repository

          ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && apt-get update

        - name: Install Docker packages

          ansible.builtin.shell: apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    - name: Add docker group and user

      block:

        - name: Add group

          ansible.builtin.group:

            name: docker

            state: present

        - name: Add user

          ansible.builtin.user:

            name: "{{ user }}"

            group: docker